version: '14.0.0.1'
services:
  web:
    #build: .
    image: odoo:14.0
    ports:
      - "8069:8069"
    volumes:
      - odoo_14_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_14_db_data:/var/lib/postgresql/data/pgdata
volumes:
  odoo_14_web_data:
  odoo_14_db_data: